"project_id": "553913"
"api_token": "06ae2424ba91f9b016befe823ae65c0f84495dbe6faf6ed51175a6a5645f8e2e98f358831a53b03a"
"base_path": "."                        # path to your project directory on a local machine
"base_url": "https://api.crowdin.com"       # https://{organization-name}.crowdin.com for Crowdin Enterprise
"preserve_hierarchy": true

"files": [
  {
      "source": "translations.json",   
      "translation": "/trans_%two_letters_code%.json",
      "type": "i18next_json"  
  },
  {
      "source": "src/assets/locales/en.json",   
      "translation": "/trans_%two_letters_code%.json",
      "type": "i18next_json"  
  }
]
